name: Executable size checker

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: Install GCC and necessary libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libx11-dev libgl1-mesa-dev libasound2-dev

      - name: Install UPX
        run: sudo apt-get install -y upx

      - name: Compile the program
        run: |
          set -e
          gcc -Os -s -ffunction-sections -fdata-sections -flto -Wl,--gc-sections,-flto ./**.c -lm -lX11 -lGL -lasound -I./include -o zoom

      - name: Check executable size and update README
        run: |
          size=$(stat -c %s zoom)
          echo "Executable size: $size bytes"
          if [ $size -gt 65536 ]; then
            echo "The executable size is greater than 64KB"
            echo "Compressing with UPX..."
            upx --best zoom
            size=$(stat -c %s zoom)
            echo "New executable size: $size bytes"
            if [ $size -gt 65536 ]; then
              echo "Error: The executable size is still greater than 64KB after compression."
              exit 1
            else
              sed -i "s/Current executable size: .*/Current executable size: $size bytes (using UPX)/" README.md
            fi
          else
            sed -i "s/Current executable size: .*\s*(using UPX)*/Current executable size: $size bytes/" README.md
          fi

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with executable size" -a || echo "No changes to commit"
          git push
